### ISSUE TITLE
Setup RabbitMQ on Titan using openshift

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#215]

**Comment by vivek-bala** [comment]
This is done for now. 
```hostname="dtn05.ccs.ornl.gov", port=30672```

**Comment by itomaldonado** [comment]
YAML files for deployment:

POD:
```
apiVersion: v1
kind: Pod
metadata:
  name: radical-entk-rmq-pod
  labels:
    app: radical-entk-rmq
spec:
  containers:
  - name: rmq
    image: "rabbitmq:3.7.3"
    imagePullPolicy: Always
    ports:
    - containerPort: 4369
      protocol: TCP
      name: tcp-4369
    - containerPort: 5671
      protocol: TCP
      name: tcp-5671
    - containerPort: 5672
      protocol: TCP
      name: tcp-5672
    - containerPort: 25672
      protocol: TCP
      name: tcp-25672
```

Service:
```
apiVersion: v1
kind: Service
metadata: 
  name: radical-entk-rmq-service
spec:
  type: NodePort
  selector:
    app: radical-entk-rmq
  ports:
  - port: 4369
    nodePort: 30369
    name: tcp-4369
  - port: 5671
    nodePort: 30671
    name: tcp-5671
  - port: 5672
    nodePort: 30672
    name: tcp-5672
  - port: 25672
    nodePort: 31672
    name: tcp-25672
```

The `hostname` is the node's hostname that is specified in the `pod` page and the port is `30672`
